export const E_CONNECT = 'RABET_EXTENSION_CONNECT';
export const E_CONNECT_RES = 'RABET_EXTENSION_CONNECT_RESPONSE';

export const E_SIGN = 'RABET_EXTENSION_SIGN';
export const E_SIGN_RES = 'RABET_EXTENSION_SIGN_RESPONSE';

export const E_CLOSE_WINDOW = 'RABET_EXTENSION_CLOSE_WINDOW';
export const E_CLOSE_WINDOW_RES = 'RABET_EXTENSION_CLOSE_WINDOW_RESPONSE';

export const E_LOGIN = 'RABET_EXTENSION_LOGIN';
export const E_NETWORK = 'RABET_EXTENSION_NETWORK';
export const E_DISCONNECT = 'RABET_EXTENSION_DISCONNECT';
export const E_IS_UNLOCKED = 'RABET_EXTENSION_IS_UNLOCKED';
export const E_LOGIN_TO_SIGN = 'RABET_EXTENSION_LOGIN_TO_SIGN';
export const E_SIGN_RESPONSE = 'RABET_EXTENSION_SIGN_XDR_RESPONSE';
export const E_CONTACT_REQUEST_RESPONSE = 'RABET_EXTENSION_CONTACT_REQUEST_RESPONSE';

export const E_GENERATED_ID = 'RABET_GENERATED_ID';
export const E_GENERATED_ID_RES = 'RABET_GENERATED_ID_RECEIVED';
